### PR TITLE
CORE-2006: dependency updates.

### PR DESCRIPTION
**Pull request by slr71**
The primary changes were:

- Update dependencies in general.
- Remove OpenTelemetry support since we're not using it.
- Update the base image for the Dockerfile (because that's required by some of our dependency updates).
- Update langohr and address any breaking changes. Thankfully this library wasn't affected by any of the breaking changes in langohr as far as I could tell.

### CODE REVIEW

**Review by ianmcorvidae — APPROVED** [review]
From what I can see, looks good. Didn't run it locally to check, but looks like the right java path and the rest all looked like straightforward dependency updates or removing otel stuff. I didn't actually remove the otel calls in the analyses service (just the agent & configuration), so I guess that could happen there, or not, at some future point. I suppose having it still in the code could theoretically mean it's still usable for local stuff, but it's possibly wishful thinking that we'd use it for local stuff anyway (or at least, in any way that wouldn't be more easily served by just adding it for that session).

**Comment by slr71** [comment]
Ah, that's a good point. I think I put the otel removal in one commit, so I could potentially restore it and fix the configuration. I may play with that tomorrow. Thanks for the review! 👍

**Comment by ianmcorvidae** [comment]
Honestly, I think removing the spans from the code is good. There's someone else's opentelemetry library for clojure that I kept meaning to switch us to anyway, so I think if we want to use otel stuff in some fashion in the future it'd be better to do it with that anyway (avoid us having to maintain our own library, however small). I just hadn't done it in `analyses` so wanted to note-to-self (or note-to-whoever-feels-like-it) that we could remove it there too.

**Comment by slr71** [comment]
Okay, that sounds reasonable to me as well.

**Comment by slr71** [comment]
I just ran this service on my workstation for a while, and it seems to be working well. I'm going to merge this now.

**Pull request merged**
